# Generated by Django 4.2.7 on 2023-11-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('register', models.BigAutoField(
                    primary_key=True, serialize=False)),
                ('first_name', models.CharField(
                    default='student-firstname', max_length=15)),
                ('last_name', models.CharField(
                    default='student-lastname', max_length=15)),
            ],
        ),
    ]
