# Generated by Django 4.2.7 on 2023-11-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostObjectsAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(default='object-name', max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('important', models.BooleanField(default=False)),
                ('place', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='LostObjectsAPI.place')),
            ],
        ),
    ]
